apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: bounajia/front-app:latest
        ports:
        - containerPort: 8083
            
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  loadBalancerIP: 172.29.0.1
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30400
  externalIPs:
    - 192.168.6.25   
      
